user nginx;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		listen ${WEB_PORT} ssl;
		http2 on;
		server_name ${DOMAIN_NAME};

		ssl_certificate     /etc/nginx/ssl/nginx.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx.key;
		ssl_protocols       TLSv1.2 TLSv1.3;
		ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;

		root /var/www/html;
		index index.php index.html;

		add_header X-Frame-Options "SAMEORIGIN";
		add_header X-Content-Type-Options "nosniff";

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			fastcgi_pass wordpress:${WP_PORT};
			fastcgi_index index.php;
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}

		location /static/ {
			proxy_pass http://static:${STATIC_PORT}/;

			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /adminer/ {
			proxy_pass http://adminer:${ADMINER_PORT}/;

			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_redirect off;
		}

		location ^~ /portainer/ {
			proxy_pass http://portainer:${PORTAINER_PORT}/;

			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;

			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

		location /portainer/api/websocket/ {
			proxy_pass http://portainer:${PORTAINER_PORT}/api/websocket/;

			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

		location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
			expires 1M;
			access_log off;
			add_header Cache-Control "public";
		}

		location ~ /\.ht {
			deny all;
		}
	}
}
