services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception_network
    restart: on-failure
    secrets:
      - db_password
      - db_root_password

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file: .env
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: on-failure
    secrets:
      - db_password
      - wp_password
      - wp_admin_password

  nginx:
    container_name: nginx
    image: nginx:inception
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - inception_network
    env_file: .env
    depends_on:
      - wordpress
    restart: on-failure

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  inception_network:
    driver: bridge
