services:
  mariadb:
    container_name: mariadb_container
    image: mariadb:inception
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
    networks:
      - inception_network
    restart: on-failure
    secrets:
      - db_password
      - db_root_password

  wordpress:
    container_name: wordpress_container
    image: wordpress:inception
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_PORT: ${WP_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - inception_network
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    secrets:
      - db_password
      - wp_password
      - wp_admin_password

  nginx:
    container_name: nginx_container
    image: nginx:inception
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - inception_network
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WEB_PORT: ${WEB_PORT}
      WP_PORT: ${WP_PORT}
    depends_on:
      - wordpress
    restart: on-failure

  # Bonus
  redis:
    container_name: redis_container
    image: redis:inception
    build: ./requirements/bonus/redis
    networks:
      - inception_network
    environment:
      REDIS_PORT: ${REDIS_PORT}
    restart: on-failure

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_WORDPRESS}
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_MARIADB} 
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_REDIS} 

networks:
  inception_network:
