events {}

http {
	server {
		listen ${ADMINER_PORT};
		root /var/www/html/adminer;
		index index.php index.html;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			fastcgi_pass wordpress:${WP_PORT};
			fastcgi_index index.php;
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
