events {}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		listen ${STATIC_PORT};
		root /var/www/static;
		index index.html;

		location / {
			try_files $uri $uri/ =404;
		}
	}
}
